image:
  name: docker/compose:latest

services:
  - docker:dind
stages:
  - production
before_script:
  - docker version
  - docker-compose version
master:
  stage: production
  only:
    - production
  script:
    - mkdir -p /home/docker/unit-conf
    - cp nginx_config.json /home/docker/unit-conf/ --verbose
    - docker image prune -f
    - docker-compose build --no-cache
    - docker-compose up -d
